#!/usr/bin/env ruby

require 'rubygems'
require 'tty-spinner'
require 'tmpdir'

require_relative 'src/Results'
require_relative 'src/checks/BrokenImages'
require_relative 'src/checks/BrokenLinks'
require_relative 'src/checks/BrokenScripts'
require_relative 'src/checks/BrokenStylesheets'
require_relative 'src/checks/Check'
require_relative 'src/checks/InvalidHTML'
require_relative 'src/checks/LogAnalyzer'
require_relative 'src/checks/PrintsErrors'
require_relative 'src/checks/PrintsLorem'
require_relative 'src/checks/URLTester'
require_relative 'src/IO/Arguments'
require_relative 'src/IO/Debugger'
require_relative 'src/IO/Formatter'
require_relative 'src/IO/usage_instructions'

# Parse command line arguments
args = Arguments.new(ARGV)
scope = args.scope
silent = args.hasAny? '--silent', '-s'
debugMode = args.hasAny? '--debug', '-d'

if args.hasAny? '--version', '-v'
    puts "awacs version 1.0.0\n" unless silent
    exit 0
end

if args.hasAny? '--help', '-h'
    usage_instructions unless silent
    exit 0
end

# Show usage instructions when no start url is given
unless scope
    usage_instructions unless silent
    exit 1
end

# --silent and --debug cannot be combined
exit 1 if (silent && debugMode)

# Fail when unknown options are encountered
unknown_options = args.unknown_options
if unknown_options.count > 0
    unknown_options.each { |o| puts "Error: unknown option #{o}" } unless silent
    exit 1
end

# Flag used to determine whether we want to show a spinner, formatted table, etc.
fancyUI = !silent && !debugMode

# Show spinner
if fancyUI
    spinner = TTY::Spinner.new "[:spinner] :operation"
    spinner.update operation: 'Initializing'
    spinner.auto_spin
end

# Initialize debug output
$d = Debugger.new debugMode

# Output variable scoped to program
results = Results.new

# Define checks to run
checks = [
    PrintsErrors.new(args),
    PrintsLorem.new(args),
    BrokenLinks.new(args),
    BrokenImages.new(args),
    BrokenStylesheets.new(args),
    BrokenScripts.new(args),
    InvalidHTML.new(args),
]
# Skip all checks marked as slow when --fast is given
checks.reject!(&:slow) if args.hasAny? '--fast', '-f'

# Create a temporary directory for us to use
spinner.update operation: 'Creating temporary directory' if fancyUI
Dir.mktmpdir do |directory|
    $d.debug "Using temporary directory #{directory}"
    spinner.update operation: 'Downloading all pages of the website' if fancyUI

    # Setup authentication if required
    auth = ""
    if args.hasAny? '--username', '--password'
        auth = "--auth-no-challenge --user=#{args.username} --password=#{args.password}"
    end

    # Download the website with wget
    wget = "(cd #{directory}; wget -r -np -nv --follow-tags=a --random-wait -erobots=off -nc -o wget.log #{auth} #{scope})"
    $d.debug "Downloading pages using wget: #{wget}"
    `#{wget}`

    # Check the wget log for errors
    spinner.update operation: 'Analyzing download log file' if fancyUI
    logFile = "#{directory}/wget.log"
    analyzer = LogAnalyzer.new logFile, results
    analyzer.analyze
    File.delete logFile

    # Iterate over all downloaded files
    spinner.update operation: 'Checking for problems in downloaded pages' if fancyUI
    files = Dir.glob("#{directory}/**/*").select {|f| !File.directory? f}
    pages = files.map do |path|
        $d.debug "processing #{path}"
        # # Read the file, feed it to all checkers
        contents = File.open(path, "r").read
        url = path.sub directory+"/", ""

        output = results.addPage url
        checks.each do |checker|
            output << checker.check(contents)
        end
        $d.debug "#{output.flatten(1).count} errors/warnings"
    end
end

# Format results
if fancyUI
    spinner.update(operation: 'All done')
    spinner.success
    spinner.update operation: 'Filtering results'

    formatter = Formatter.new results, args.hasAny?('--errors', '-e'), args.hasAny?('--warnings', '-w')
    puts formatter.render
end

# Exit with proper return code
if results.hasErrors?
    $d.debug "done, found errors"
    exit 2
elsif results.hasWarnings?
    $d.debug "done, found warnings"
    exit 3
else
    $d.debug "done, found no errors and no warnings"
    exit 0
end
