#!/usr/bin/env ruby

require 'rubygems'
require 'tty-table'
require 'tty-spinner'
require 'tmpdir'

require_relative 'src/Formatter.rb'
require_relative 'src/Debugger.rb'
require_relative 'src/Results.rb'
require_relative 'src/checks/PrintsErrors.rb'

# Parse command line arguments
scope = ARGV.shift
errorsOnly = ARGV.include? '--errors-only'
silent = ARGV.include? '--silent'
debugMode = ARGV.include? '--debug'

# Show usage instructions when no start url is given
if !scope || scope.start_with?('-')
    puts "Usage: bfc [scope] [options]" unless silent
    puts "Scope should be a website directory, e.g. http://in10.nl/nieuws" unless silent
    puts "Options: --silent, --debug, --errors-only. See readme.md" unless silent
    exit 1
end

if (silent && debugMode)
    exit 1
end

# Fail when unknown options are encountered
unknown_options = ARGV - ['--errors-only', '--silent', '--debug']
if unknown_options.count > 0
    unless silent
        unknown_options.each do |option|
            puts "Error: unknown option #{option}"
        end
    end
    exit 1
end

# Flag used to determine whether we want to show a spinner, formatted table, etc.
fancyUI = !silent && !debugMode

# Show spinner
if fancyUI
    spinner = TTY::Spinner.new "[:spinner] :operation"
    spinner.update operation: 'Initializing'
    spinner.auto_spin
end

# Initialize debug output
d = Debugger.new debugMode

# Output variable scoped to program
results = Results.new

# Define checks to run
checks = [PrintsErrors.new]

# Create a temporary directory for us to use
spinner.update operation: 'Creating temporary directory' if fancyUI
Dir.mktmpdir do |directory|
    d.debug "Using temporary directory #{directory}"
    spinner.update operation: 'Downloading all pages of the website' if fancyUI

    # Download the website with wget
    wget = "(cd #{directory}; wget --quiet --recursive --no-parent --follow-tags=a --random-wait -erobots=off #{scope})"
    d.debug "Downloading pages using wget: #{wget}"
    `#{wget}`

    # Iterate over all downloaded files
    spinner.update operation: 'Checking for problems' if fancyUI
    files = Dir.glob("#{directory}/**/*").select {|f| !File.directory? f}
    pages = files.map do |path|
        d.debug "processing #{path}"
        # # Read the file, feed it to all checkers
        contents = File.open(path, "r").read
        url = path.sub directory+"/", ""

        output = results.addPage url
        checks.each do |checker|
            output << checker.check(contents)
        end
        d.debug "#{output.flatten(1).count} errors/warnings"
    end
end

# Format results
if fancyUI
    spinner.update(operation: 'All done')
    spinner.success
    spinner.update operation: 'Filtering results'

    formatter = Formatter.new results, errorsOnly
    data = formatter.tableData

    if data.count > 0
        table = TTY::Table.new ['Path', 'Results'], data
        puts "Results"
        puts table.render :ascii, multiline: true
    else
        puts "No pages contained errors and/or warnings"
    end
end

# Exit with proper return code
if results.hasErrors?
    d.debug "done, found errors"
    exit 2
elsif results.hasWarnings?
    d.debug "done, found warnings"
    exit 3
else
    d.debug "done, found no errors and no warnings"
    exit 0
end
