#!/usr/bin/env ruby

require 'rubygems'
require 'tty-table'
require 'tty-spinner'
require 'tmpdir'

require_relative 'src/Formatter.rb'
require_relative 'src/Results.rb'
require_relative 'src/checks/PrintsErrors.rb'

# Parse command line arguments
scope = ARGV[0]
errorsOnly = ARGV.include? '--errors-only'
silent = ARGV.include? '--silent'

# Show usage instructions when no start url is given
unless scope
    puts "Usage: bfc [scope]" unless silent
    puts "Scope should be a website directory, e.g. http://in10.nl/nieuws" unless silent
    exit 1
end

# Show spinner
unless silent
    spinner = TTY::Spinner.new "[:spinner] :operation"
    spinner.update operation: 'Initializing'
    spinner.auto_spin
end

# Output variable scoped to program
results = Results.new

# Define checks to run
checks = [PrintsErrors.new]

# Create a temporary directory for us to use
spinner.update operation: 'Creating temporary directory' unless silent
Dir.mktmpdir do |directory|
    spinner.update operation: 'Downloading all pages of the website' unless silent
    # Download the website with wget
    `(cd #{directory}; wget --quiet --recursive --no-parent --follow-tags=a --random-wait -erobots=off #{scope})`

    # Iterate over all downloaded files
    spinner.update operation: 'Checking for problems' unless silent
    files = Dir.glob("#{directory}/**/*").select {|f| !File.directory? f}
    pages = files.map do |path|
        # # Read the file, feed it to all checkers
        contents = File.open(path, "r").read
        url = path.sub directory+"/", ""

        output = results.addPage url
        checks.each do |checker|
            output << checker.check(contents)
        end
    end
end

# Format results
unless silent
    spinner.update(operation: 'All done')
    spinner.success
    spinner.update operation: 'Filtering results'

    formatter = Formatter.new results, errorsOnly
    data = formatter.tableData

    if data.count > 0
        table = TTY::Table.new ['Path', 'Results'], data
        puts "Results"
        puts table.render :ascii, multiline: true
    else
        puts "No pages contained errors and/or warnings"
    end
end

# Exit with proper return code
if results.hasErrors?
    exit 2
elsif results.hasWarnings?
    exit 3
else
    exit 0
end
