def usage_instructions
    puts "awacs version 1.0.0"
    puts "Crawl through a domain and check every page for errors"
    puts "Usage: awacs [scope] [options]"
    puts "Scope should be a website directory, e.g. https://www.in10.nl/nieuws"
    puts "Options:"
    puts "  -f, --fast        Skip slow tests"
    puts ""
    puts "  -e, --errors      Show pages with errors"
    puts "  -w, --warnings    Show pages with warnings"
    puts ""
    puts "  -s, --silent      Suppress all output, returning only an exit code"
    puts "  -d, --debug       Verbose action output, no visual effects"
    puts ""
    puts "  --username        HTTP Basic Authentication username"
    puts "  --password        HTTP Basic Authentication password"
    puts ""
    puts "  -h, --help        These usage instructions"
    puts "  -v, --version     Version number"
end
